"A" <-
function (x) 
{
    if (!(class(x) == "varest")) {
        stop("\nPlease provide an object of class 'varest', generated by 'var()'.\n")
    }
    K <- x$K
    p <- x$p
    A <- B(x)[, 1:(K*p)]
    As <- list()
    start <- seq(1, p * K, K)
    end <- seq(K, p * K, K)
    for (i in 1:p) {
        As[[i]] <- matrix(A[, start[i]:end[i]], nrow = K, ncol = K)
        rownames(As[[i]]) <- rownames(A)
        colnames(As[[i]]) <- colnames(A[, start[i]:end[i]])
    }
    return(As)
}
