"B" <-
function(x){
  if(!(class(x)=="varest")){
    stop("\nPlease provide an object of class 'varest', generated by 'var()'.\n")
  }
  y.names <- colnames(x$datamat[, c(1 : x$K)])
  Z <- x$datamat[, -c(1 : x$K)]
  B <- matrix(0, nrow = x$K, ncol = ncol(Z))
  if(is.null(x$restriction)){
    for(i in 1 : x$K){
      B[i, ] <- coef(x$varresult[[i]])
    }
  }else if(!(is.null(x$restriction))){
    for(i in 1 : x$K){
      restrictions <- x$restrictions
      restrictions[i, restrictions[i, ] == TRUE] <- coef(x$varresult[[i]])
      temp <- restrictions[i, ]
      B[i, ] <- temp
    }
  }
  colnames(B) <- colnames(Z)
  rownames(B) <- y.names
  return(B)
}
